-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Keyring and auth



-- XDG Desktop Portals


-- Clipboard history



-- Auto delete trash 30 days old


-- Cursors




-- Location provider and night light



-- Forward bluetooth media commands to MPRIS


-- Axctl daemon (sécurité — ambxst le lance via AxctlService, mais au cas où)


-- Watcher: met à jour les couleurs Hyprland quand le wallpaper change


-- Watcher: met à jour le bind Super+F selon le layout


-- Nettoyage des sockets Wayland orphelins à la déconnexion

-- Évite l'écran noir quand on switch vers KDE ou un autre DE


-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("gnome-keyring-daemon --start --components=secrets")
    hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
    hl.exec_cmd("sleep 1 && systemctl --user restart xdg-desktop-portal xdg-desktop-portal-hyprland xdg-desktop-portal-gtk")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("trash-empty 30")
    hl.exec_cmd("hyprctl setcursor " .. cursorTheme .. " " .. cursorSize)
    hl.exec_cmd("gsettings set org.gnome.desktop.interface cursor-theme '" .. cursorTheme .. "'")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface cursor-size " .. cursorSize)
    hl.exec_cmd("/usr/lib/geoclue-2.0/demos/agent")
    hl.exec_cmd("gammastep")
    hl.exec_cmd("mpris-proxy")
    hl.exec_cmd("sleep 3 && axctl -c ~/.local/share/ambxst/axctl.toml daemon")
    hl.exec_cmd("sleep 2 && ~/.config/hypr/scripts/scheme-watcher.sh")
    hl.exec_cmd("~/.config/hypr/scripts/layout_bind_watcher.sh")
end)

-- Shutdown
hl.on("hyprland.shutdown", function()
    hl.exec_cmd("bash -c 'rm -f/run/user/$(id -u)/wayland-1/run/user/$(id -u)/wayland-1.lock; rm -rf/run/user/$(id -u)/hypr'")
end)
