general {
    # Géré par ambxst (dwindle, master, ou scrolling)
    # layout = dwindle

    allow_tearing = true  # GPU: Reduces input lag for gaming (tearing OK)

    gaps_workspaces = $workspaceGaps
    gaps_in = $windowGapsIn
    gaps_out = $windowGapsOut
    border_size = $windowBorderSize

    col.active_border = $activeWindowBorderColour
    col.inactive_border = $inactiveWindowBorderColour
}

dwindle {
	preserve_split = true
	smart_split = false
	smart_resizing = true
}
