-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- ############# Themes #############

-- Force GTK3 theming pour Qt/KDE apps → adw-gtk3-dark

hl.env("QT_QPA_PLATFORMTHEME", "gtk3")

hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", 1)

hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", 1)

hl.env("XCURSOR_THEME", cursorTheme)

hl.env("XCURSOR_SIZE", cursorSize)

-- ######## Toolkit backends ########

hl.env("GDK_BACKEND", "wayland,x11")

hl.env("QT_QPA_PLATFORM", "wayland")

hl.env("SDL_VIDEODRIVER", "wayland,x11,windows")

hl.env("CLUTTER_BACKEND", "wayland")

hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")

-- ####### XDG specifications #######

hl.env("XDG_CURRENT_DESKTOP", "Hyprland")

hl.env("XDG_SESSION_TYPE", "wayland")

hl.env("XDG_SESSION_DESKTOP", "Hyprland")

hl.env("XDG_PICTURES_DIR", os.getenv("HOME") .. "/Images")

hl.env("XDG_VIDEOS_DIR", os.getenv("HOME") .. "/Vidéos")

hl.env("XDG_DOCUMENTS_DIR", os.getenv("HOME") .. "/Documents")

hl.env("XDG_DOWNLOAD_DIR", os.getenv("HOME") .. "/Téléchargements")

hl.env("XDG_MUSIC_DIR", os.getenv("HOME") .. "/Musique")

hl.env("XDG_TEMPLATES_DIR", os.getenv("HOME") .. "/Modèles")

hl.env("XDG_PUBLICSHARE_DIR", os.getenv("HOME") .. "/Public")

hl.env("XDG_DESKTOP_DIR", os.getenv("HOME") .. "/Bureau")

-- ############# Others #############

hl.env("_JAVA_AWT_WM_NONREPARENTING", 1)

-- ############# GPU (Vulkan partout) #############

hl.env("GBM_BACKEND", "drm")

hl.env("LIBVA_DRIVER_NAME", "radeonsi")

hl.env("VDPAU_DRIVER", "radeonsi")

hl.env("MESA_VK_WSI_PRESENT_MODE", "mailbox")

hl.env("RADV_PERFTEST", "aco")

-- ############# Firefox #############

hl.env("MOZ_ENABLE_WAYLAND", 1)

hl.env("MOZ_DISABLE_RDD_SANDBOX", 1)

-- ############# Qt/Quickshell (OpenGL — Vulkan non supporté par QuickShell sur Stoney) #############

hl.env("QSG_RENDER_LOOP", "threaded")

hl.env("QSG_BACKEND", "opengl")

hl.env("QT_QUICK_BACKEND", "opengl")

hl.env("NIXOS_OZONE_WL", 1)
