# This file contains dynamically generated window rules for opaque classes.
windowrule = opacity 1.0 override 1.0 override, match:class ^(kitty)$
windowrule = opacity 0.85 override 0.85 override, match:class ^(kdesystemsettings)$
windowrule = opacity 0.85 override 0.85 override, match:class ^(org.kde.plasma-systemmonitor)$
windowrule = opacity 0.85 override 0.85 override, match:class ^(org.quickshell)$
windowrule = opacity 0.85 override 0.85 override, match:class ^(org.kde.kate)$
windowrule = opacity 0.85 override 0.85 override, match:class ^(org.kde.plasma.emojier)$
windowrule = opacity 0.85 override 0.85 override, match:class ^(org.kde.ark)$
windowrule = opacity 0.85 override 0.85 override, match:class ^(org.kde.dolphin)$
windowrule = opacity 0.85 override 0.85 override, match:class ^(be.alexandervanhee.gradia)$
